# Lecture 2. TensorFlow Ops



In [153]:
import numpy as np
import pandas as pd
import tensorflow as tf

np.random.seed(0)

## Constants, sequences, variables, ops

It is very easy to make a constant in TF.

In [154]:
# A 1D vector constant.
a = tf.constant([2, 2], name='vector')
a

<tf.Tensor: id=598, shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [155]:
# A 2D matrix constant.
b = tf.constant([[0, 1], [2, 3]], name='matrix')
b

<tf.Tensor: id=599, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

There are a lot of convience functions for creating data structures of different dimensions.

In [156]:
# A 2x3 matrix of zeros.
tf.zeros([2, 3], tf.int32)

<tf.Tensor: id=602, shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [157]:
# Make a zeros constant of the same shape as another object.
tf.zeros_like(b)

<tf.Tensor: id=603, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [158]:
# There is a simillar function for ones.
tf.ones([2, 3], tf.int32)

<tf.Tensor: id=606, shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [159]:
tf.ones_like(b)

<tf.Tensor: id=609, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [160]:
# Make an n-array of any shape with a custom fill value.
tf.fill([2, 3], 8)

<tf.Tensor: id=612, shape=(2, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [161]:
# Make an array from a sequence.
tf.linspace(10.0, 13.0, 4, name='lin-space')

<tf.Tensor: id=616, shape=(4,), dtype=float32, numpy=array([10., 11., 12., 13.], dtype=float32)>

In [162]:
tf.range(start=3, limit=18, delta=3)

<tf.Tensor: id=620, shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

In [163]:
tf.range(start=3, limit=1, delta=-0.5)

<tf.Tensor: id=626, shape=(4,), dtype=float32, numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

In [164]:
tf.range(5)

<tf.Tensor: id=630, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

There are various functions for creating random data: `random_normal()`, `truncated_normal()`, `​random_uniform()`, `​random_shuffle()`, `​random_crop()`, `​multinomial()`, `​random_gamma()`, and `​set_random_seed()`.

In [165]:
tf.random.normal(shape=[10], mean=10, stddev=1.0, seed=0, name='normal')

<tf.Tensor: id=636, shape=(10,), dtype=float32, numpy=
array([ 9.439541 , 11.0533085,  8.805745 , 10.948302 ,  7.985449 ,
       10.12768  ,  9.485002 ,  9.848843 , 10.739277 , 10.438746 ],
      dtype=float32)>

## Math Operations

There are a bunch of various division functions.

In [166]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')

tf.math.divide(a, b)

<tf.Tensor: id=641, shape=(2, 2), dtype=float64, numpy=
array([[       inf, 2.        ],
       [1.        , 0.66666667]])>

## Variables

Differences between constants are variables:

1. A constant does not change.
2. A constant's value is stored *with* the model graph whereas a variable is stored separately.

### Creating variables

Note that the function for creating a variable is `tf.Variable()` with an uppercase "V" because it is a class.
The `tf.constant()` function uses a lowercase "c" because it is an ops, not a class.

At the time of writting this course, TF encouraged developers to use the wrapper `get_variable()` to create a variable.
Here is the general structure:

```python
tf.get_variable(
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=None,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None
)
```

However, as of TF 2.0, they now suggest using `tf.Variable()`, directly.
Creating a variable is shown below.

In [167]:
s = tf.Variable(tf.constant(2), 'scalar')
s

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [168]:
m = tf.Variable([[0, 1], [2, 3]], 'matrix')
m

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [169]:
W = tf.Variable(tf.zeros([10, 10]), 'big_matrix')
W

<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [170]:
W.eval

<bound method BaseResourceVariable.eval of <tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>>

A variable can be assigned a value using the `assign()` method.

In [171]:
W.assign(tf.random.normal([10, 10]))
W

<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=
array([[ 0.02936255, -0.86747646, -0.8452195 , -0.26652253,  0.11087855,
         0.41120422,  0.92334676, -0.33460006, -0.85756123,  0.8442435 ],
       [ 0.26037455, -0.17688881,  0.1632508 ,  0.44674233,  1.3234712 ,
         1.3052758 , -0.8651197 ,  1.2339976 , -1.3227814 ,  0.9247735 ],
       [-0.41094947,  0.7952504 , -1.7627925 , -1.2065858 ,  1.0230845 ,
        -0.22552626, -1.1214129 ,  0.74185956,  1.1253291 ,  1.1326234 ],
       [ 1.3066211 , -0.33423454,  0.9824326 ,  1.1420981 , -0.39754665,
         0.99293154,  0.24455707, -0.7633621 , -0.12773935,  0.32760194],
       [ 1.4027779 ,  0.36471343, -1.790517  ,  0.34080747, -1.1352329 ,
         0.40419906, -1.4473691 ,  0.8261736 , -2.2291663 ,  0.85217124],
       [ 1.774641  , -0.20230924, -0.44129497,  0.6964944 , -0.926713  ,
         0.3398413 ,  0.8431046 ,  0.5213242 ,  0.3134696 , -0.16407096],
       [ 2.230049  , -1.863732  , -0.3128602 , -0.31636

In [172]:
a = tf.Variable(2, 'scalar')
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [173]:
a.assign(a * 2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>

In [174]:
a.assign(a * 2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=8>

In [175]:
a.assign_add(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=10>

In [176]:
a.assign_sub(3)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>