# Chapter 13. Introduction to Modeling Libraries in Python

## 13.1 Interfacing between pandas and model code

Use the `.values` property to turn a pandas DataFrame to a numpy array.

In [157]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)

%matplotlib inline

In [158]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [159]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [160]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

A numpy array can easily be converted back to a pandas DataFrame.

In [161]:
df2 = pd.DataFrame(data.values, columns=['one', 'two', 'three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

Use the `loc()` method to select a subset of columns.

In [162]:
model_cols = ['x0', 'x1']
data.loc[:, model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

The next example demonstrates the process of turning a categorical column into columns of dummary variables.

In [163]:
# Add a Categorical column
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [164]:
# Create a dummy DataFrame and join the reuslt.
dummies = pd.get_dummies(data.category, prefix='category')
dummies

category_a  category_b
0           1           0
1           0           1
2           1           0
3           1           0
4           0           1

In [165]:
data_with_dummies = data.drop('category', axis=1).join(dummies)
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

## 13.2 Creating model descriptions with Patsy

The Patsy library is for describing statistical models in an R-like syntax.

In [166]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [167]:
import patsy

y, X = patsy.dmatrices('y ~ x0 + x1', data)
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [168]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [169]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [170]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

The  intercept can be suppressed by adding a `+ 0` term.

In [171]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

The Patsy design matrix can be passed directly to algorithms like the `linalg.lstsq()` method from numpy.

In [172]:
coef, resid, _, _ = np.linalg.lstsq(X, y, rcond=None)
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [173]:
resid

array([19.63791494])

In [174]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

### Data transformations in Patsy formulae

Python code can be in a Patsy formula string.

In [175]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

Some common transofrmations include `standardize()` and `center()` which sets the mean to 0 with standard deviation to 1 and substracting the mean, respectively.

In [176]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data=data)
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

The transformations for the training data should be repeated, but not recalculated, for the test data.
Patsy can do these transformations of the test data using the values from the training data.

In [177]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]
})
new_data

x0   x1  y
0   6  3.1  1
1   7 -0.5  2
2   8  0.0  3
3   9  2.3  4

In [178]:
new_X = patsy.build_design_matrices([X.design_info], new_data)
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

Because the `+` symbol in Patsy formulae do not mean to add the columns, if this is the desired behaviour, the `I()` function must be used.

In [179]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data=data)
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

### Categorical data and Patsy

Patsy converts categorical data to dummy variables automatically.
If there is an intercept, one of the levels will be left out to avoid colinearity.

In [180]:
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1':[1,2,3,4,5,6,7,8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})

y, X = patsy.dmatrices('v2 ~ key1', data=data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [181]:
# Without an intercept.
y, X = patsy.dmatrices('v2 ~ 0 + key1', data=data)
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

A numerical column can be interpreted as a categorical variable using the `C()` function.

In [182]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data=data)
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

With multiple terms, we can introduce interactions.

In [183]:
# Add a new categorical column.
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [184]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data=data)
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [185]:
# Interaction terms are expressed with the `a:b` notation like in R.
y, X  = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data=data)
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

## 13.3 Introduction to statsmodels

The statsmodels library is used to fit many kinds of statistical models (mainly frequentist), perform statistical tests, and data exploration and visualization.

### Estimating linear models

There are two main APIs for statsmodels, one is array-based and the other formula-based.

In [186]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Some random data for example modeling.
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

# For reproducibility
np.random.seed(12345)

N=100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]

eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [187]:
y[:5]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109])

The `sm.add_constant()` function can add a column for the intercept.

In [188]:
X_model = sm.add_constant(X)
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

The `sm.OLS()` class can fit an OLS linear regression.

In [189]:
model = sm.OLS(y, X)
model

In [190]:
result = model.fit()
result

In [191]:
result.aic

74.60927884012554

In [192]:
print(result.summary())

OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Fri, 15 Nov 2019   Prob (F-statistic):                    7.44e-12
Time:                        22:22:30   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------

In [193]:
# Access the model's coefficients.
result.params

array([0.17826108, 0.22303962, 0.50095093])

The following is a simillar example using the formula API.
Note how an intercept is automatically included.

In [194]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])
data['y'] = y
data[:5]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941

In [195]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()
print(results.summary())

OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     24.68
Date:                Fri, 15 Nov 2019   Prob (F-statistic):           6.37e-12
Time:                        22:22:30   Log-Likelihood:                -33.835
No. Observations:                 100   AIC:                             75.67
Df Residuals:                      96   BIC:                             86.09
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0336      0.035      0.952      0.343      -0.036       0.104
c

In [196]:
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

The `y` for new data can be predicted using the model, too.

In [197]:
results.predict(data[:5])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
dtype: float64

## 13.4 Introduction to scikit-learn

The scikit-lean library contains a broad selection of supervised and unsupervised machine learning methods.
The example below is about passenger survival rates on the Titanic.

In [198]:
# Load training data.
train = pd.read_csv('assets/datasets/titanic/train.csv')

# Load test data.
test = pd.read_csv('assets/datasets/titanic/test.csv')

train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [199]:
# Check for missing data.
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [200]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

There is missing data for age, so we will do a simple method of imputation and use the median value of the training data.

In [201]:
# Median age of training data for imputing missing values.
impute_value = train.Age.median()

# Fill in missing data for training and testing data.
train['Age'] = train.Age.fillna(impute_value)
test['Age'] = test.Age.fillna(impute_value)

An `'IsFemale'` column is created as a dummy for `'Sex'`.

In [202]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

The features for the model will be 'Pclass', 'IsFemale', and 'Age'.

In [203]:
predictors = ['Pclass', 'IsFemale', 'Age']
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train.Survived.values

X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [204]:
y_train[:5]

array([0, 1, 1, 1, 0])

For the purposes of demonstration, a logistic regression model was used.

In [205]:
from sklearn.linear_model import LogisticRegression

# Instantiate model.
model = LogisticRegression()

# Fit the model.
model.fit(X_train, y_train)

/opt/anaconda3/envs/daysOfCode-env/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

The testing data can be fed to the fit model for making predictions.

In [206]:
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

Below is an example of using cross-validation to test the accuracy of a model without using the testing data.

In [207]:
from sklearn.linear_model import LogisticRegressionCV

model_cv = LogisticRegressionCV(10, cv=10)
model_cv.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=10, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='warn', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [208]:
y_predict_cv = model_cv.predict(X_test)

We can actually see that this model made a few different predictions on the testing set than the original model without cross-validation.

In [209]:
idx = y_predict_cv != y_predict
sum(idx)

10

In [210]:
test.iloc[idx]

PassengerId  Pclass                                   Name     Sex   Age  \
41           933       1            Franklin, Mr. Thomas Parham    male  28.0   
94           986       1                    Birnbaum, Mr. Jakob    male  25.0   
146         1038       1            Hilliard, Mr. Herbert Henry    male  28.0   
148         1040       1              Crafton, Mr. John Bertram    male  28.0   
191         1083       1                 Salomon, Mr. Abraham L    male  28.0   
205         1097       1              Omont, Mr. Alfred Fernand    male  28.0   
252         1144       1               Clark, Mr. Walter Miller    male  27.0   
266         1158       1  Chisholm, Mr. Roderick Robert Crispin    male  28.0   
290         1182       1    Rheims, Mr. George Alexander Lucien    male  28.0   
313         1205       3                    Carr, Miss. Jeannie  female  37.0   

     SibSp  Parch      Ticket      Fare Cabin Embarked  IsFemale  
41       0      0      113778   26.5500   D34        S         0  
94       0      0       13905   26.0000   NaN        C         0  
146      0      0       17463   51.8625   E46        S         0  
148      0      0      113791   26.5500   NaN        S         0  
191      0      0      111163   26.0000   NaN        S         0  
205      0      0  F.C. 12998   25.7417   NaN        C         0  
252      1      0       13508  136.7792   C89        C         0  
266      0      0      112051    0.0000   NaN        S         0  
290      0      0    PC 17607   39.6000   NaN        S         0  
313      0      0      368364    7.7500   NaN        Q         1